name: Compile TDLib for Android

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build_android:
    name: Build TDLib for Android
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - name: Checkout TDLib Source Code
        uses: actions/checkout@v4
        with:
          repository: tdlib/td # Specify the TDLib repository
          path: tdlib_source # Checkout into a specific directory

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # zulu, adopt
          java-version: '17'

      - name: Install dependencies (Required by TDLib build scripts)
        run: sudo apt update && sudo apt install -yq php php-cli gperf g++ git perl make unzip wget sed

      - name: Fetch Android SDK
        working-directory: tdlib_source/example/android
        run: |
          ./fetch-sdk.sh
          ANDROID_SDK_HOME="$ANDROID_SDK_ROOT"
          ANDROID_NDK_ROOT="$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION"

      - name: Build OpenSSL for Android (All Archs)
        working-directory: tdlib_source/example/android
        run: ./build-openssl.sh

      - name: Archive Compiled OpenSSL Libraries
        uses: actions/upload-artifact@v4
        with:
          name: OpenSSL-all_arch-binaries
          path: tdlib_source/example/android/third-party
          retention-days: 7

      - name: Build TDLib for Android (ARM64)
        working-directory: tdlib_source/example/android
        run: |
          sed -i.bak 's/\(for ABI in \).* ;/\1arm64-v8a ;/g' build-tdlib.sh
          ./build-tdlib.sh

      - name: List some files 2
        working-directory: tdlib_source/example/android
        run: find . -maxdepth 5

      - name: Archive Compiled TDLib Libraries
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-ARM64-binaries
          path: |
           tdlib_source/example/android/tdlib/tdlib.zip
           tdlib_source/example/android/build-native-Java
           tdlib_source/example/android/build-arm64-v8a-Java/lib*.so
           tdlib_source/example/android/build-arm64-v8a-Java/lib*.so.debug
          retention-days: 7
